
export const ROUTER_TRANSITION_ACTIONS = {
  TRANSITION_FADE: 'TRANSITION_FADE',
  TRANSITION_POP: 'TRANSITION_POP',
  TRANSITION_SLIDE_LEFT: 'TRANSITION_SLIDE_LEFT',
  TRANSITION_SLIDE_RIGHT: 'TRANSITION_SLIDE_RIGHT',
  TRANSITION_NO_ANIMATION: 'TRANSITION_NO_ANIMATION',
};

export const MESSAGE_ACTIONS = {
  ADD_QUESTION: 'ADD_QUESTION',
};
